replicaCount: 1

image:
  repository: hello-app
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

service:
  type: NodePort
  port: 8000
  nodePort: 30080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /management/healthz
    port: 8000
  periodSeconds: 3
readinessProbe:
  httpGet:
    path: /management/ready
    port: 8000
  periodSeconds: 3

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  # targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

env:
  - name: DATABASE_URL
    value: sqlite://

nodeSelector: {}

tolerations: []

affinity: {}
